In [3]:
import pandas as pd 
import numpy as np

In [12]:
#path to eZTrack data 

ezTrackLocations = r'/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscopeLinearTrack/2025.4/m328/2025_04_10_328_15_59_58_b2/My_WebCam/2025_04_10_328_15_59_58_b2_rotated_cropped_output_LocationOutput.csv'
ezTrack = alignedTraces = pd.read_csv(ezTrackLocations)

#path to aligned eZTrack data
dirPath = '/Users/johnmarshall/Documents/Analysis/miniscope_analysis/miniscopeLinearTrack/2025.4/m328/2025_04_10_328_15_59_58_b2/'
alignedFile = '1_24_motion_corrected_JJM_5_9_25cellTracesAlignedToTracking.csv'
#load calcium signal aligned to tracking data 
alignedTraces = pd.read_csv(dirPath+alignedFile)

In [7]:
alignedTracesLocationData = alignedTraces[['closestBehavCamFrameIdx', 'X_coor', 'Y_coor']]

In [15]:
ezTrack[['X', 'Y']][0:50]

             X          Y
0   646.160325  20.247228
1   645.131117  19.839175
2   645.342843  19.225590
3   644.350702  18.985817
4   643.659900  18.418524
5   645.182606  18.553392
6   645.347159  19.194678
7   646.712114  19.301775
8   645.459967  19.623795
9   645.005257  19.635689
10  640.968706  19.828195
11  639.043355  19.676948
12  637.831107  19.940801
13  635.940971  19.873520
14  635.386164  19.846391
15  633.289421  19.618939
16  626.901451  18.899133
17  620.122233  19.346630
18  613.158743  19.267124
19  603.405588  19.361990
20  596.091427  19.512230
21  587.036586  19.230030
22  579.491681  18.889365
23  568.069082  19.418678
24  561.603843  19.345053
25  554.966582  19.085738
26  545.313527  19.523461
27  537.141835  19.138833
28  527.078445  18.386184
29  517.674615  18.467439
30  504.741084  18.157978
31  500.410945  17.075401
32  491.849482  17.072283
33  483.280153  17.184399
34  475.234533  17.047374
35  463.924199  17.619401
36  457.522005  17.569805
37  449.452269  17.011628
38  439.470185  16.806046
39  432.189420  17.282385
40  425.340221  16.595443
41  416.640946  16.684247
42  407.539300  17.015852
43  398.804084  16.901405
44  391.108087  16.327960
45  381.539206  16.407187
46  373.298395  17.014434
47  365.467071  16.376017
48  357.966589  15.769715
49  350.065709  15.767154

In [10]:
alignedTracesLocationData[0:50]

    closestBehavCamFrameIdx      X_coor     Y_coor
0                         0  646.160325  20.247228
1                         1  645.131117  19.839175
2                         2  645.342843  19.225590
3                         3  644.350702  18.985817
4                         4  643.659900  18.418524
5                         4  643.659900  18.418524
6                         5  643.659900  18.418524
7                         6  645.182606  18.553392
8                         7  645.347159  19.194678
9                         8  646.712114  19.301775
10                        9  645.459967  19.623795
11                       10  645.005257  19.635689
12                       10  645.005257  19.635689
13                       11  640.968706  19.828195
14                       12  640.968706  19.828195
15                       13  639.043355  19.676948
16                       14  637.831107  19.940801
17                       15  635.940971  19.873520
18                       16  635.386164  19.846391
19                       17  633.289421  19.618939
20                       17  633.289421  19.618939
21                       18  626.901451  18.899133
22                       19  620.122233  19.346630
23                       20  620.122233  19.346630
24                       21  613.158743  19.267124
25                       22  603.405588  19.361990
26                       23  596.091427  19.512230
27                       23  596.091427  19.512230
28                       24  587.036586  19.230030
29                       25  579.491681  18.889365
30                       26  568.069082  19.418678
31                       27  568.069082  19.418678
32                       28  561.603843  19.345053
33                       29  554.966582  19.085738
34                       30  545.313527  19.523461
35                       30  545.313527  19.523461
36                       31  537.141835  19.138833
37                       32  527.078445  18.386184
38                       33  517.674615  18.467439
39                       34  504.741084  18.157978
40                       35  504.741084  18.157978
41                       36  500.410945  17.075401
42                       36  500.410945  17.075401
43                       37  491.849482  17.072283
44                       38  483.280153  17.184399
45                       39  475.234533  17.047374
46                       40  463.924199  17.619401
47                       41  457.522005  17.569805
48                       42  457.522005  17.569805
49                       43  449.452269  17.011628